### ISSUE TITLE
Support for Bitbucket

### ISSUE THREAD

**Issue by vanto** [noelboss/deepl.io#2]
Support for Bitbucket would make a great addition. The payload for Webhooks has changed recently and its definition can be found [here](https://confluence.atlassian.com/display/BITBUCKET/Event+Payloads).

**Comment by noelboss** [comment]
Thanx, i will integrate it on the next release, or if you want, you can fork and integrate it yourself; 
This checks the repo type (would probably better check http headers...);
https://github.com/noelboss/deepl.io/blob/master/app/deeplio/Deeplio.php#L54

Function run does the heavy lifting;
https://github.com/noelboss/deepl.io/blob/master/app/deeplio/Deeplio.php#L65-L140

**Comment by noelboss** [comment]
Added this by Integrated Changes from natronite-bitbucket_dev
