### ISSUE TITLE
Issue connecting to the server

### ISSUE THREAD

**Issue by coffeeneed** [noelboss/deepl.io#3]
I'm new to Git, but I'm learning as I go. So thanks for trying your script :) Though I have some difficulties getting it work (I have no idea if the problems occur because of mod_rewrite or php exec).

My story:
1. Script is cloned via Github and is located at www.mydomain.com/deploy
2. Webhook made on GitHub and is set as www.mydomain.com/deploy/<token> (the token set in config)
3. The same key is set as secret in the hook. application/json is set, trigger is just "push the event" and Active is checked.

When doing this and pushing to master I unforunately get 404 error under webhooks in Github:

Request URL: http://www.mydomain.com/deploy/<token>
Request method: POST
content-type: application/json
Expect: 
User-Agent: GitHub-Hookshot/8b1477d
X-GitHub-Delivery: 20386c80-20e0-11e5-8205-db9ea32af80c
X-GitHub-Event: push
X-Hub-Signature: sha1=063617fb859c437a40a4076ef616985ac662c77f

Content-Length: 0
Content-Type: text/html
Date: Thu, 02 Jul 2015 17:33:03 GMT
Server: Apache/2.2.16
Vary: Accept-Encoding

deepl.oi error log says this:

[2015-07-02 19:33:04 - IP 192.30.252.34]
[ERROR] Security token not correct: deploy/<token>
[STATUS] FAILED – Deployment not finished!
[NOTR] No mails configured.

Can you figure out what is wrong with this? I think it's strange. It looks like the token is incorrect, but it certainly is not. However, it's strange it thinks that the deploy folder (path to deeplio) is a part of the token?

Any ideas, please? :)

Cheers!

**Comment by noelboss** [comment]
Yep, the Secret at GitHub is not used, instead enter the following url as your "Payload URL";
www.mydomain.com/deploy/your-sec-token/

I will change this behaviour in the future...

your mod_rewrite works, otherwise you would not get any log entry....

**Comment by coffeeneed** [comment]
Thanks for your answer.
I removed the secret in the GitHub webhook panel, but it doesn't work either way :(

Besides that I notice a wrong copy and paste in my post. The log says this:

```
[2015-07-03 00:38:00 - IP 192.30.252.45]
[ERROR] Security token not correct: deploy/ASDhui3hAS998sdASJJFs9ahf983hfAHfkjh
[STATUS] FAILED – Deployment not finished!
[NOTR] No mails configured.
```

Of course, the long code is the token I made, which is also in the config.

I still get the error messages reported.I didn't totally get if you know what's wrong or not (?)

Additional info:
    "repository_ssh_url": "git@github.com:coffeeneed/maggy.git",
    "branch": "master"

This is a private repo. Tried open too.

**Comment by noelboss** [comment]
does 0.5.1 work for your?

**Comment by coffeeneed** [comment]
I tried 0.5.1 now. Doesn't work.

```
Headers
Content-Length: 0
Content-Type: text/html
Date: Fri, 03 Jul 2015 06:14:06 GMT
Server: Apache/2.2.16
Vary: Accept-Encoding
```

Body is empty.

I suspect this has something to do with the shared hosting? Maybe there is a difference/distance between the web server and the shell server. Just a though.
