### ISSUE TITLE
Docs incomplete/outdated

### ISSUE THREAD

**Issue by frennkie** [noelboss/deepl.io#6]
I finally managed to get this to work with Gitlab.
I think having a little more documentation (and also fixing some of the outdated remarks) would really help.

Example for outdated (or even wrong?!):

> You can test this by calling /admin/ (protected by .htaccess, only works localy)

The way I managed to get it working the admin page is available at `https://deploy.example.com/app/admin/public` and **is not available only for localhost**. The .htaccess includes `Allow From All`.

Also the release download link is not working.

I noticed that there is a fork (https://github.com/natronite/deepl.io) which has some good improvements (e.g. allowing IP Ranges instead of single IPs only) - any plans to incorporate those commits?

**Comment by noelboss** [comment]
I did integrate the features…
