### ISSUE TITLE
Tag version 0.9.0

### ISSUE THREAD

**Issue by geertw** [noelboss/deepl.io#7]
Release v0.9.0 is mentioned in commits, changelog and README.md, but it's not tagged. Therefore the link to the release doesn't work and users download an old version.

Could you please tag version v0.9.0?

**Comment by noelboss** [comment]
I have taged 0.9 and 0.10 Thanks for looking into it. Do you use it?

**Comment by geertw** [comment]
Thanks! I was in the process of setting it up, and then discovered the missing tags. Now continuing the installation :-)

**Comment by noelboss** [comment]
Great, if you find bugs or anything you wish to add, just create a branch and a push request, I'll try to implement it…
